#Deployment of Container1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
  labels:
    app: container1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
        - name: container1
          image: jay411/container1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data-volume
              mountPath: /jay_PV_dir
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: host-pvc

---

# Service for Container1
apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  selector:
    app: container1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---

# Claim for host-pv for both containers
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi